// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string leaderboard_world_defenders = "CgkIl6DK5sQfEAIQBw"; // <GPGSID>
        public const string achievement_highscore_king = "CgkIl6DK5sQfEAIQAg"; // <GPGSID>
        public const string achievement_millionaires_club = "CgkIl6DK5sQfEAIQAA"; // <GPGSID>
        public const string achievement_ghostmusic_memeber = "CgkIl6DK5sQfEAIQBA"; // <GPGSID>
        public const string achievement_g_membership = "CgkIl6DK5sQfEAIQAw"; // <GPGSID>
        public const string achievement_billionaires_boys_club = "CgkIl6DK5sQfEAIQBQ"; // <GPGSID>

}

